const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('admin/index.html','utf8');
const source=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n').replace(/\bboot\(\);\s*$/,'');
const elements={};const timers=[];const calls=[];const removed=[];let replies=[];
function element(){const classes=new Set(['hidden']);return {textContent:'',appendChild(){},addEventListener(){},classList:{add:v=>classes.add(v),remove:v=>classes.delete(v),contains:v=>classes.has(v)}}}
const context=vm.createContext({Date,AbortController,console,
 document:{addEventListener(){},getElementById:id=>elements[id]||=element(),
 createElement:()=>({}),createTextNode:text=>({textContent:text})},
 localStorage:{getItem:()=> 'test-session',removeItem:key=>removed.push(key)},
 setTimeout:(fn,delay)=>{timers.push(delay);return timers.length;},clearTimeout(){},
 fetch:async(url,options)=>{calls.push({url,options});const next=replies.shift();if(next instanceof Error)throw next;return {ok:next.status>=200&&next.status<300,status:next.status,json:async()=>next.data};}});
vm.runInContext(source,context);
(async()=>{
 const started=Date.now();
 replies=[{status:404},{status:200,data:{workflow_runs:[{id:123,status:'completed',conclusion:'success',created_at:new Date(started).toISOString(),html_url:'https://github.com/esign2015/mp-tenders/actions/runs/123'}]}}];
 await context.pollWorkflow('data_refresh',0,started);
 assert(elements.workflowState.textContent.includes('सफल'));
 assert.equal(calls.length,2);
 assert(!calls[1].options.headers,'Admin token never sent to public GitHub');
 assert(!timers.includes(90000),'Completed runs stop polling');
 replies=[{status:200,data:{workflow_runs:[]}}];timers.length=0;
 await context.pollWorkflow('data_refresh',0,started);
 assert(elements.workflowState.textContent.includes('प्रतीक्षा'));
 assert(timers.includes(90000),'No run yet must keep polling');
 replies=[{status:403}];timers.length=0;
 await context.pollWorkflow('data_refresh',0,started);
 assert(!elements.workflowState.textContent.includes('session समाप्त'),'Public API limits do not mean admin logout');
 assert(timers.includes(90000));
 replies=[new TypeError('Failed to fetch')];timers.length=0;
 await context.pollWorkflow('data_refresh',0,started);
 assert(elements.workflowState.textContent.includes('असफल होना तय नहीं'));
 assert(timers.includes(90000),'Network failure must retry');
 replies=[{status:200,data:{workflow_runs:[{id:124,status:'completed',conclusion:'failure',created_at:new Date(started).toISOString()}]}}];
 await context.pollWorkflow('data_refresh',0,started);
 assert(elements.workflowState.textContent.includes('असफल'));
 replies=[{status:200,data:{workflow_runs:[{id:99,created_at:new Date(started-60000).toISOString()}]}}];
 const old=await context.workflowStatus('data_refresh',started);
 assert.equal(old.id,undefined,'Previous run cannot be reported as the requested run');
 const loadStats=context.loadAdminStats;context.loadAdminStats=()=>{};
 context.showPanel('admin.name@example.com');
 assert.equal(elements.adminEmail.textContent,'admin.name@example.com');
 assert.equal(elements.adminEmail.title,'admin.name@example.com');
 assert.equal(elements.adminAvatar.textContent,'AN');
 assert(!elements.adminSession.classList.contains('hidden'));
 assert(elements.login.classList.contains('hidden'));
 assert(!elements.panel.classList.contains('hidden'));
 context.logout();
 assert(elements.adminSession.classList.contains('hidden'));
 assert(elements.panel.classList.contains('hidden'));
 assert(!elements.login.classList.contains('hidden'));
 assert.equal(elements.adminEmail.textContent,'');
 assert.equal(elements.adminEmail.title,'');
 assert.equal(removed.at(-1),'mp_admin_session');
 assert.equal((html.match(/id="adminEmail"/g)||[]).length,1);
 assert(html.indexOf('id="adminSession"')<html.indexOf('</header>'));
 context.loadAdminStats=loadStats;elements.panel.classList.remove('hidden');
 replies=[{status:200,data:{ok:true,stats:{total_users:1250,today_signups:5,today_active_users:12,today_returning_users:7,updated_at:'2026-10-02T17:00:00+05:30'}}}];
 await context.loadAdminStats();
 assert.equal(elements.statTotalUsers.textContent,'1,250');
 assert.equal(elements.statTodaySignups.textContent,'5');
 assert.equal(elements.statTodayActive.textContent,'12');
 assert.equal(elements.statTodayReturning.textContent,'7');
 assert(elements.statsStatus.textContent.includes('IST'));
 assert(timers.includes(300000));
 replies=[{status:503,data:{ok:false,message:'Storage unavailable'}}];
 await context.loadAdminStats();
 assert.equal(elements.statTotalUsers.textContent,'1,250','Storage errors keep the last known numbers');
 assert.equal(elements.statsStatus.textContent,'Storage unavailable');
 const schedule=context.setTimeout;
 context.setTimeout=(fn,delay)=>{if(delay===2000)Promise.resolve().then(fn);return schedule(fn,delay)};
 replies=[{status:202,data:{ok:true,pending:true}},{status:200,data:{ok:true,stats:{total_users:1251,today_signups:6,today_active_users:13,today_returning_users:7,updated_at:'2026-10-02T17:01:00+05:30'}}}];
 const pendingBefore=calls.length;await context.loadAdminStats();
 assert.equal(calls.length,pendingBefore+2);
 assert(calls[pendingBefore].url.endsWith('?refresh=1'));
 assert(calls[pendingBefore+1].url.endsWith('/api/admin/stats'));
 assert.equal(elements.statTotalUsers.textContent,'1,251');
 context.setTimeout=schedule;
 let complete;context.fetch=(url,options)=>{calls.push({url,options});return new Promise(resolve=>complete=resolve)};
 const before=calls.length,pending=context.loadAdminStats();await context.loadAdminStats();
 assert.equal(calls.length,before+1,'Repeated refresh cannot create overlapping requests');
 context.logout();assert(calls.at(-1).options.signal.aborted);
 complete({ok:true,json:async()=>({ok:true,stats:{total_users:9,today_signups:9,today_active_users:9,today_returning_users:0,updated_at:'2026-10-02T17:01:00+05:30'}})});
 await pending;
 assert.equal(elements.statTotalUsers.textContent,'—','Delayed responses cannot restore counters after logout');
 console.log('PASS: missing Render endpoint falls back to real GitHub status; no-run/network retry, failed-run display, stale-run exclusion, no token leakage.');
 console.log('PASS: header admin profile appears on login/restore and hides with email cleared on logout.');
 console.log('PASS: real stats are formatted, refreshes cannot overlap, storage failure preserves old data and logout cancels and ignores late responses.');
})().catch(e=>{console.error(e);process.exitCode=1;});
