const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('index.html','utf8');assert(html.includes('enforceAccountAccess().then'));assert(!html.includes('enforceTelegramAccess().then'));assert(html.includes('logoutBtn.onclick=()=>localStorage.getItem(VISITOR_SESSION_KEY)?accountLogout():logoutTelegram()'));
for(const source of [html,fs.readFileSync('admin/index.html','utf8')])for(const script of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);
const nodes={},local=new Map(),session=new Map();let now=Date.parse('2026-10-02T09:00:00+05:30');const node=id=>nodes[id]??={value:'',hidden:false,textContent:'',classList:{toggle(){},add(){},remove(){}},addEventListener(e,h){this[e]=h},reportValidity(){return true},querySelector(){return this.button??={disabled:false,setAttribute(){}}},appendChild(child){(this.children??=[]).push(child)},replaceChildren(){this.children=[]},removeAttribute(name){delete this[name]},setAttribute(){}};
let fail=true,unlocked=false,opened='',reply=null,postCount=0;
const ctx=vm.createContext({visitorNode:node,VISITOR_SESSION_KEY:'token',VISITOR_PROFILE_KEY:'profile',Date:{now:()=>now},setInterval(){return 1},clearInterval(){},sessionStorage:{getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},visitorUnlock:data=>{unlocked=true;local.set('token',data.session_token)},location:{hash:'',pathname:'/',search:'',reload(){}},history:{replaceState(){}},window:{open:url=>opened=url,addEventListener(){}},document:{body:{classList:{add(){}}},addEventListener(){},createElement:()=>({})},alert(){},fetch:async(url,options)=>{
 if(url.endsWith('/ready'))return{ok:true,json:async()=>({ok:true})};
 assert(!url.includes('/telegram/'));if(url.includes('mp_tehsils'))return{json:async()=>({districts:{Dewas:['Kannod','Bagli'],Datia:['Datia'],Indore:['Indore']}})};
 postCount++;const body=JSON.parse(options.body);
 if(reply)return reply;
 if(url.endsWith('/forgot-check'))return{ok:true,json:async()=>({ok:true})};
 if(fail)return{ok:false,status:401,json:async()=>({message:'wrong password'})};
 return{ok:true,json:async()=>({ok:true,session_token:'account-token',visitor_id:'user-id',profile:{name:'Test',mobile:'+919876543210',district:'Dewas'}})};
}});
vm.runInContext(fs.readFileSync('assets/account_access.js','utf8'),ctx);
for(const [input,expected] of [['6000000000','6000000000'],['9999999999','9999999999'],['5999999999',''],['abc98765-x43210','9876543210'],['+91 9876543210','9876543210'],['987654321012','9876543210']])assert.equal(ctx.accountMobileValue(input),expected);
for(const [input,expected] of [['9876543210',''],['कुमार१२३','कुमार'],['Kumar123','Kumar'],['O’Neil','O’Neil'],['कुमार','कुमार'],['Ram@12','Ram']])assert.equal(ctx.accountMiddleNameValue(input),expected);
assert(html.indexOf('id="visitorMobile"')<html.indexOf('id="visitorName"'));
(async()=>{
 const pending=ctx.enforceAccountAccess();await new Promise(r=>setImmediate(r));
 assert(!node('accountSignInForm').hidden);assert(node('accountSignUpForm').hidden);
 for(const name of ['SignIn','SignUp','Forgot'])assert.equal(node('account'+name+'Form').querySelector().disabled,true);
 node('accountLoginMobile').value='9876543210';node('accountSignInForm').input();assert.equal(node('accountSignInForm').querySelector().disabled,true);
 node('accountLoginPassword').value='Private1!';node('accountSignInForm').input();assert.equal(node('accountSignInForm').querySelector().disabled,false);
 ctx.accountSetBusy('SignIn',true);node('accountSignInForm').input();assert.equal(node('accountSignInForm').querySelector().disabled,true);
 const before=postCount;await node('accountSignInForm').submit({preventDefault(){},currentTarget:node('accountSignInForm')});assert.equal(postCount,before);
 ctx.accountSetBusy('SignIn',false);node('accountLoginPassword').value='';node('accountSignInForm').input();assert.equal(node('accountSignInForm').querySelector().disabled,true);
 node('accountForgotMobile').value='98765';node('accountForgotForm').input();assert.equal(node('accountForgotForm').querySelector().disabled,true);
 node('accountForgotMobile').value='9876543210';node('accountForgotForm').input();assert.equal(node('accountForgotForm').querySelector().disabled,false);node('accountForgotMobile').value='';node('accountForgotForm').input();

 node('visitorDistrict').value='d';node('visitorDistrict').input();assert.deepEqual(node('visitorDistrictList').children.map(option=>option.value),['Dewas','Datia']);
 node('visitorDistrict').value='de';node('visitorDistrict').input();assert.deepEqual(node('visitorDistrictList').children.map(option=>option.value),['Dewas']);
 node('visitorDistrict').value='dez';node('visitorDistrict').input();assert.equal(node('visitorDistrict').value,'de');
 node('visitorDistrict').value='Dewas';node('visitorDistrict').input();assert.equal(node('visitorTehsil').disabled,false);
 node('visitorTehsil').value='k';node('visitorTehsil').input();assert.deepEqual(node('visitorTehsilList').children.map(option=>option.value),['Kannod']);
 node('visitorTehsil').value='kez';node('visitorTehsil').input();assert.equal(node('visitorTehsil').value,'k');node('visitorTehsil').blur();assert.equal(node('visitorTehsil').value,'');
 node('visitorDistrict').value='Datia';node('visitorDistrict').input();assert.deepEqual(node('visitorTehsilList').children.map(option=>option.value),['Datia']);
 node('visitorDistrict').value='d';node('visitorDistrict').input();node('visitorDistrict').blur();assert.equal(node('visitorDistrict').value,'');assert.equal(node('visitorTehsil').disabled,true);
 for(const id of ['visitorMiddleName','accountEditMiddleName']){node(id).value='Kumar123';node(id).input();assert.equal(node(id).value,'Kumar')}
 node('accountSignUpTab').onclick();assert(!node('accountSignUpForm').hidden);assert(node('accountSignInForm').hidden);
 node('accountForgotTab').onclick();node('accountForgotMobile').value='9876543210';await node('accountForgotForm').submit({preventDefault(){},currentTarget:node('accountForgotForm')});assert.equal(opened,'');assert(node('accountForgotWhatsApp').href.startsWith('https://wa.me/919893610244?text='));assert.equal(node('accountForgotWhatsApp').hidden,false);
 node('accountForgotMobile').input();assert(node('accountForgotWhatsApp').hidden);assert(!node('accountForgotWhatsApp').href);
 node('accountSignInTab').onclick();node('accountLoginMobile').value='9876543210';node('accountLoginPassword').value='Private1!';
 let finishCheck;
 reply={ok:false,status:401,json:()=>new Promise(resolve=>finishCheck=resolve)};
 const waitingLogin=node('accountSignInForm').submit({preventDefault(){},currentTarget:node('accountSignInForm')});
 await new Promise(r=>setImmediate(r));
 assert(!node('accountLoginLoading').hidden);assert.equal(node('telegramGate').inert,true);
 finishCheck({ok:false,message:'wrong password'});await waitingLogin;
 assert(node('accountLoginLoading').hidden);assert.equal(node('telegramGate').inert,false);reply=null;
 await node('accountSignInForm').submit({preventDefault(){},currentTarget:node('accountSignInForm')});assert(!unlocked);assert(!local.has('token'));
 reply={ok:false,status:404,json:async()=>({ok:false,code:'signup_required',message:'Sign up required'})};
 await node('accountSignInForm').submit({preventDefault(){},currentTarget:node('accountSignInForm')});
 assert(!node('accountSignUpForm').hidden);assert.equal(node('visitorMobile').value,'9876543210');assert.equal(node('accountNewPassword').value,'Private1!');assert(!unlocked);
 node('visitorName').value='Test';node('visitorLastName').value='Surname';node('visitorDistrict').value='Dewas';node('visitorTehsil').value='Kannod';node('accountConfirmPassword').value='Private1!';
 node('accountConfirmPassword').value='Different1!';node('accountSignUpForm').input();assert.equal(node('accountSignUpForm').querySelector().disabled,true);
 node('accountConfirmPassword').value='Private1!';node('accountSignUpForm').input();assert.equal(node('accountSignUpForm').querySelector().disabled,false);
 node('visitorLastName').value='';node('accountSignUpForm').input();assert.equal(node('accountSignUpForm').querySelector().disabled,true);node('visitorLastName').value='Surname';node('visitorMiddleName').value='';node('accountSignUpForm').input();assert.equal(node('accountSignUpForm').querySelector().disabled,false);
 node('visitorTehsil').value='Indore';node('accountSignUpForm').change();assert.equal(node('accountSignUpForm').querySelector().disabled,true);node('visitorTehsil').value='Kannod';node('accountSignUpForm').change();assert.equal(node('accountSignUpForm').querySelector().disabled,false);
 let finishSignup;
 reply={ok:false,status:409,json:()=>new Promise(resolve=>finishSignup=resolve)};
 const waitingSignup=node('accountSignUpForm').submit({preventDefault(){},currentTarget:node('accountSignUpForm')});
 await new Promise(r=>setImmediate(r));
 assert(!node('accountLoginLoading').hidden);assert.equal(node('telegramGate').inert,true);assert.equal(node('accountLoadingTitle').textContent,'Sign up हो रहा है…');
 finishSignup({ok:false,code:'account_exists',message:'Already registered'});await waitingSignup;
 assert(node('accountLoginLoading').hidden);assert.equal(node('telegramGate').inert,false);
 assert(!node('accountSignInForm').hidden);assert.equal(node('accountLoginMobile').value,'9876543210');assert.equal(node('accountLoginPassword').value,'');assert.equal(node('accountNewPassword').value,'');
 reply={ok:false,status:404,json:async()=>({ok:false,code:'signup_required',message:'Sign up first'})};
 node('accountForgotTab').onclick();node('accountForgotMobile').value='9123456789';
 await node('accountForgotForm').submit({preventDefault(){},currentTarget:node('accountForgotForm')});
 assert(!node('accountSignUpForm').hidden);assert.equal(node('visitorMobile').value,'9123456789');assert(node('accountForgotWhatsApp').hidden);assert.equal(opened,'');
 node('accountSignInTab').onclick();node('accountLoginPassword').value='Private1!';
 reply=null;fail=false;await node('accountSignInForm').submit({preventDefault(){},currentTarget:node('accountSignInForm')});await pending;assert(unlocked);assert.equal(node('accountLoginPassword').value,'');assert(node('accountLoginLoading').hidden);assert.equal(node('telegramGate').inert,false);
 node('accountProfileBtn').onclick();assert.equal(node('accountEditName').value,'Test');assert.equal(node('accountEditMobile').value,'+919876543210');
 // Historical names must be confirmed and saved before unlock.
 unlocked=false;local.delete('token');
 ctx.accountShowLoginLoading(true);
 const correction=ctx.accountUnlock({session_token:'repair-token',visitor_id:'user-id',profile:{first_name:'Test',middle_name:'9876543210',last_name:'',name:'Test 9876543210',mobile:'+919876543210',district:'Dewas'},profile_corrections:['last_name','middle_name']});
 await new Promise(r=>setImmediate(r));assert(!unlocked);assert(!node('accountRepairForm').hidden);assert(node('accountTabs').hidden);assert.equal(node('accountRepairName').value,'Test');assert.equal(node('accountRepairMiddleName').value,'9876543210');assert(node('accountLoginLoading').hidden);assert.equal(node('telegramGate').inert,false);
 reply={ok:false,status:400,json:async()=>({ok:false,message:'Correct middle name'})};
 await node('accountRepairForm').onsubmit({preventDefault(){}});assert(!unlocked);assert(!local.has('token'));
 node('accountRepairMiddleName').value='';node('accountRepairLastName').value='Surname';
 reply={ok:true,json:async()=>({ok:true,profile:{name:'Test Surname',first_name:'Test',middle_name:'',last_name:'Surname',district:'Dewas',mobile:'+919876543210'},profile_corrections:[]})};
 await node('accountRepairForm').onsubmit({preventDefault(){}});await correction;assert(unlocked);assert.equal(local.get('token'),'repair-token');reply=null;
 const activityBeforeRefresh=local.get('mp_account_activity_v1');ctx.accountSetupControls({profile:{name:'Test',mobile:'9876543210'},new_login:false});assert.equal(local.get('mp_account_activity_v1'),activityBeforeRefresh);
 now=Date.parse('2026-10-02T23:29:59+05:30');assert.equal(ctx.accountExpired(),false);now+=1000;assert.equal(ctx.accountExpired(),true);assert(!local.has('token'));assert(session.get('mp_account_notice').includes('12:30'));
 assert.equal(ctx.accountMaintenanceActive(Date.parse('2026-10-03T00:29:59+05:30')),true);assert.equal(ctx.accountMaintenanceActive(Date.parse('2026-10-03T00:30:00+05:30')),false);ctx.accountApplyMaintenance();assert(!node('accountMaintenanceNotice').hidden);assert(node('accountSignInForm').hidden);
 now=Date.parse('2026-10-03T00:30:00+05:30');ctx.accountApplyMaintenance();assert(node('accountMaintenanceNotice').hidden);assert(!node('accountSignInForm').hidden);
 local.set('token','another-token');reply={ok:false,status:401,json:async()=>({message:'Logged in on another device'})};await ctx.accountCheckSession();assert(!local.has('token'));assert.equal(session.get('mp_account_notice'),'Logged in on another device');
 local.set('token','retry-token');reply={ok:false,status:503,json:async()=>({message:'Temporary unavailable'})};await ctx.accountCheckSession();assert.equal(local.get('token'),'retry-token');ctx.accountLogout();assert(!local.has('token'));
 console.log('PASS: logout handler, profile controls, daily 23:30 IST logout, maintenance until 00:30 IST and refresh keeps the session and signup routing preserves mobile/password, duplicate signup returns to signin with mobile only, unknown forgot cannot open WhatsApp, registered forgot link, failed login stays locked and successful login clears passwords.');
})().catch(e=>{console.error(e);process.exitCode=1});
